version: '3.4'

services:
  jupyter:
    environment:
      - AWS_REGION=${DEBUG}
      - AWS_PROFILE=${AWS_PROFILE}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-server
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/home/notebooks"
      - "~/.aws:/root/.aws:ro"
    command:
      - jupyter
      - notebook
      - "--ip=0.0.0.0"
      - "--allow-root"
      - "--no-browser"